apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app: metastore
spec:
  ports:
  - port: 9083
    name: metastore
  clusterIP: None
  selector:
    app: metastore
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-metastore
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: metastore # has to match .spec.template.metadata.labels
  serviceName: "metastore"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: metastore # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: metastore
        image: docker.io/library/hivemetastore:3.0.0
        command: ["sh", "-c", "/entrypoint.sh"]
        ports:
        - containerPort: 9083
          name: metastore
        env:
        - name: METASTORE_TYPE
          value: postgres
        - name: GCS_PROJECT_ID
          value: ""
        - name: GCS_JSON_KEY_FILE_PATH
          value: ""
        - name: GCS_DEFAULT_PATH
          value: ""
        - name: AWS_S3_ENDPOINT
          value: "http://minio:9000"
        - name: AWS_S3_ACCESS_KEY
          value: "minio"
        - name: AWS_S3_SECRET_KEY
          value: "minio123"
        - name: METASTORE_THRIFT_URIS
          value: "thrift://hive-metastore:9083"
        - name: METASTORE_DB_CONNECTION_URL
          value: "jdbc:postgresql://postgresql:5432/hive_db"
        - name: METASTORE_DB_CONNECTION_USER
          value: "admin"
        - name: METASTORE_DB_CONNECTION_PASSWORD
          value: "admin"
        - name: METASTORE_DB_HOSTNAME
          value: postgresql